# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: strawberry
day_night: true
font: ''
font_size: S

# SEO
site_type: Person
local_business_type: ''
org_name: 'Rolando Campusano'
twitter: ''
description: 'Economist with research interests in the intersection of entrepreneurship, urban economics, and industrial organization.'

# Contact (edit or remove options as required)
email: rolando.campusano@rotman.utoronto.ca
address:
  street: 105 St George St, Toronto, ON M5S 3E6
  city: Toronto
  region: Ontario
  postcode: 'M4W3G0'
  country: Canada
  country_code: CA
coordinates:
  latitude: '43.665991237886615'
  longitude: '-79.39857036931312'

# Override the theme's font set (optional).
#   Latest font sets (may require updating): https://sourcethemes.com/academic/themes/
#   Browse built-in font sets in `themes/academic/data/fonts/`
#   Browse user installed font sets in `data/fonts/`
#font: "custom_fonts"

# Site header
main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: false
  highlight_active_link: true
  logo: 'rotman-logo'

# Localization
date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features
highlight: true
highlight_languages:
  - r
  - python
math: true
diagram: true
privacy_pack: false
edit_page:
  repo_url: 'https://github.com/rcampusa/website'
  content_dir: ''
  repo_branch: master
  editable:
    page: true
    post: true
    book: false
show_related:
  book: false
  page: false
  post: false
  project: true
  publication: false
  event: true
reading_time: true
section_pager: true
docs_section_pager: true
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: ''
abstract_length: 1000
plugins_js: []
avatar:
  gravatar: true
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: false
comments:
  provider: ''
  commentable:
    post: false
    book: false
    project: false
    publication: false
    event: false
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: '3'
  api_key: 'pk.eyJ1IjoicmNhbXB1c2EiLCJhIjoiY2t0eXNnZGx1MGR0NzJ2b3dpb2hjcmJpMyJ9.1HAcVw-jg1DixIog1jW1Vw'
  zoom: 15
marketing:
  google_analytics: 'UA-126228217-1'
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: master
  local_backend: false
icon:
  pack:
    ai: true
    fas: true
    fab: true
